### ISSUE TITLE
How can I copy text from OCR recognition results?

### ISSUE THREAD

**Issue by ezKernel** [Greedysky/TTKOCR#10]
This tool looks great. But how can I copy text from OCR recognition results? I have build the software in Linuxmint 20.3 (Ubuntu 20.04). But I can't find a way to copy the recognition results. Would anyone help me ?
![TTKOCR](https://github.com/Greedysky/TTKOCR/assets/90443149/ceae9cde-e520-40df-aab2-bebb68b3edaf)

**Comment by Greedysky** [comment]
You can try latest commit a9d24917c1fdb67d92e9d4a57d0854cdb6306ad6
