### ISSUE TITLE
Q:图像预处理

### ISSUE THREAD

**Issue by SuperChrisliu** [Greedysky/TTKOCR#2]
我用了一下，识别效果挺好的，牛逼，还以为是基于[tesseract](https://github.com/tesseract-ocr/tesseract)的。你这个识别的算法是自己写的吗？使用tesseract时对图片的预处理很重要，比如二值化，膨胀腐蚀，，，

我猜这个项目里识别时应该也有预处理吧，用了哪些图像处理的算法呢，对这样的图片
http://7xkg1e.com1.z0.glb.clouddn.com/1.jpg

识别准确率还有提升的空间吗？

**Comment by Greedysky** [comment]
现在暂时还没有做图像的处理，后期会加入

**Comment by SuperChrisliu** [comment]
看了一下代码本地没有做识别
